// Code generated by proto-gen-vine. DO NOT EDIT.
// source: github.com/vine-io/gpm/api/service/gpm/v1/gpm.proto

package gpmv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/vine-io/gpm/api/types/gpm/v1"
	client "github.com/vine-io/vine/core/client"
	registry "github.com/vine-io/vine/core/registry"
	server "github.com/vine-io/vine/core/server"
	api "github.com/vine-io/vine/lib/api"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// API Endpoints for GpmService service
func NewGpmServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		&api.Endpoint{
			Name:        "GpmService.Info",
			Description: "GpmService.Info",
			Path:        []string{"/api/v1/info"},
			Method:      []string{"GET"},
			Body:        "*",
			Handler:     "rpc",
		},
		&api.Endpoint{
			Name:        "GpmService.ListService",
			Description: "GpmService.ListService",
			Path:        []string{"/api/v1/Service"},
			Method:      []string{"GET"},
			Body:        "*",
			Handler:     "rpc",
		},
		&api.Endpoint{
			Name:        "GpmService.GetService",
			Description: "GpmService.GetService",
			Path:        []string{"/api/v1/Service/{name}"},
			Method:      []string{"GET"},
			Body:        "*",
			Handler:     "rpc",
		},
		&api.Endpoint{
			Name:        "GpmService.CreateService",
			Description: "GpmService.CreateService",
			Path:        []string{"/api/v1/Service"},
			Method:      []string{"POST"},
			Body:        "*",
			Handler:     "rpc",
		},
		&api.Endpoint{
			Name:        "GpmService.EditService",
			Description: "GpmService.EditService",
			Path:        []string{"/api/v1/Service/{name}"},
			Method:      []string{"PATCH"},
			Body:        "*",
			Handler:     "rpc",
		},
		&api.Endpoint{
			Name:        "GpmService.StartService",
			Description: "GpmService.StartService",
			Path:        []string{"/api/v1/Service/{name}/action/start"},
			Method:      []string{"PATCH"},
			Body:        "*",
			Handler:     "rpc",
		},
		&api.Endpoint{
			Name:        "GpmService.StopService",
			Description: "GpmService.StopService",
			Path:        []string{"/api/v1/Service/{name}/action/stop"},
			Method:      []string{"PATCH"},
			Body:        "*",
			Handler:     "rpc",
		},
		&api.Endpoint{
			Name:        "GpmService.RebootService",
			Description: "GpmService.RebootService",
			Path:        []string{"/api/v1/Service/{name}/action/reboot"},
			Method:      []string{"PATCH"},
			Body:        "*",
			Handler:     "rpc",
		},
		&api.Endpoint{
			Name:        "GpmService.DeleteService",
			Description: "GpmService.DeleteService",
			Path:        []string{"/api/v1/Service/{name}"},
			Method:      []string{"DELETE"},
			Body:        "*",
			Handler:     "rpc",
		},
		&api.Endpoint{
			Name:        "GpmService.ListServiceVersions",
			Description: "GpmService.ListServiceVersions",
			Path:        []string{"/api/v1/Service/{name}/versions"},
			Method:      []string{"GET"},
			Body:        "*",
			Handler:     "rpc",
		},
		&api.Endpoint{
			Name:        "GpmService.RollBackService",
			Description: "GpmService.RollBackService",
			Path:        []string{"/api/v1/Service/{name}/rollback"},
			Method:      []string{"POST"},
			Body:        "*",
			Handler:     "rpc",
		},
		&api.Endpoint{
			Name:        "GpmService.Ls",
			Description: "GpmService.Ls",
			Path:        []string{"/api/v1/Action/ls"},
			Method:      []string{"GET"},
			Body:        "*",
			Handler:     "rpc",
		},
		&api.Endpoint{
			Name:        "GpmService.Exec",
			Description: "GpmService.Exec",
			Path:        []string{"/api/v1/Action/exec"},
			Method:      []string{"POST"},
			Body:        "*",
			Handler:     "rpc",
		},
	}
}

// Swagger OpenAPI 3.0 for GpmService service
func NewGpmServiceOpenAPI() *registry.OpenAPI {
	return &registry.OpenAPI{
		Openapi: "3.0.1",
		Info: &registry.OpenAPIInfo{
			Title:       "GpmServiceService",
			Description: "OpenAPI3.0 for GpmService",
			Version:     "v1.0.0",
		},
		Servers: []*registry.OpenAPIServer{},
		Tags: []*registry.OpenAPITag{
			&registry.OpenAPITag{
				Name:        "GpmService",
				Description: "OpenAPI3.0 for GpmService",
			},
		},
		Paths: map[string]*registry.OpenAPIPath{
			"/api/v1/Action/exec": &registry.OpenAPIPath{
				Post: &registry.OpenAPIPathDocs{
					Tags:        []string{"GpmService"},
					Summary:     "远程执行命令",
					Description: "GpmService Exec",
					OperationId: "GpmServiceExec",
					RequestBody: &registry.PathRequestBody{
						Description: "Exec ExecReq",
						Content: &registry.PathRequestBodyContent{
							ApplicationJson: &registry.ApplicationContent{
								Schema: &registry.Schema{
									Ref: "#/components/schemas/v1.ExecReq",
								},
							},
						},
					},
					Responses: map[string]*registry.PathResponse{
						"200": &registry.PathResponse{
							Description: "successful response (stream response)",
							Content: &registry.PathRequestBodyContent{
								ApplicationJson: &registry.ApplicationContent{
									Schema: &registry.Schema{Ref: "#/components/schemas/v1.ExecRsp"},
								},
							},
						},
					},
					Security: []*registry.PathSecurity{},
				},
			},
			"/api/v1/Action/ls": &registry.OpenAPIPath{
				Get: &registry.OpenAPIPathDocs{
					Tags:        []string{"GpmService"},
					Summary:     "获取目录信息下文件列表",
					Description: "GpmService Ls",
					OperationId: "GpmServiceLs",
					Parameters: []*registry.PathParameters{
						&registry.PathParameters{
							Name:        "path",
							In:          "query",
							Description: "LsReq field path",
							Required:    true,
							Style:       "form",
							Explode:     true,
							Schema: &registry.Schema{
								Type: "string",
							},
						},
					},
					Responses: map[string]*registry.PathResponse{
						"200": &registry.PathResponse{
							Description: "successful response (stream response)",
							Content: &registry.PathRequestBodyContent{
								ApplicationJson: &registry.ApplicationContent{
									Schema: &registry.Schema{Ref: "#/components/schemas/v1.LsRsp"},
								},
							},
						},
					},
					Security: []*registry.PathSecurity{},
				},
			},
			"/api/v1/Service": &registry.OpenAPIPath{
				Get: &registry.OpenAPIPathDocs{
					Tags:        []string{"GpmService"},
					Summary:     "查询所有服务",
					Description: "GpmService ListService",
					OperationId: "GpmServiceListService",
					Parameters:  []*registry.PathParameters{},
					Responses: map[string]*registry.PathResponse{
						"200": &registry.PathResponse{
							Description: "successful response (stream response)",
							Content: &registry.PathRequestBodyContent{
								ApplicationJson: &registry.ApplicationContent{
									Schema: &registry.Schema{Ref: "#/components/schemas/v1.ListServiceRsp"},
								},
							},
						},
					},
					Security: []*registry.PathSecurity{},
				},
				Post: &registry.OpenAPIPathDocs{
					Tags:        []string{"GpmService"},
					Summary:     "新建服务",
					Description: "GpmService CreateService",
					OperationId: "GpmServiceCreateService",
					RequestBody: &registry.PathRequestBody{
						Description: "CreateService CreateServiceReq",
						Content: &registry.PathRequestBodyContent{
							ApplicationJson: &registry.ApplicationContent{
								Schema: &registry.Schema{
									Ref: "#/components/schemas/v1.CreateServiceReq",
								},
							},
						},
					},
					Responses: map[string]*registry.PathResponse{
						"200": &registry.PathResponse{
							Description: "successful response (stream response)",
							Content: &registry.PathRequestBodyContent{
								ApplicationJson: &registry.ApplicationContent{
									Schema: &registry.Schema{Ref: "#/components/schemas/v1.CreateServiceRsp"},
								},
							},
						},
					},
					Security: []*registry.PathSecurity{},
				},
			},
			"/api/v1/Service/{name}": &registry.OpenAPIPath{
				Delete: &registry.OpenAPIPathDocs{
					Tags:        []string{"GpmService"},
					Summary:     "删除服务",
					Description: "GpmService DeleteService",
					OperationId: "GpmServiceDeleteService",
					Parameters: []*registry.PathParameters{
						&registry.PathParameters{
							Name:        "name",
							In:          "path",
							Description: "DeleteServiceReq field name",
							Required:    true,
							Explode:     true,
							Schema: &registry.Schema{
								Type: "string",
							},
						},
					},
					Responses: map[string]*registry.PathResponse{
						"200": &registry.PathResponse{
							Description: "successful response (stream response)",
							Content: &registry.PathRequestBodyContent{
								ApplicationJson: &registry.ApplicationContent{
									Schema: &registry.Schema{Ref: "#/components/schemas/v1.DeleteServiceRsp"},
								},
							},
						},
					},
					Security: []*registry.PathSecurity{},
				},
				Get: &registry.OpenAPIPathDocs{
					Tags:        []string{"GpmService"},
					Summary:     "查询单个服务",
					Description: "GpmService GetService",
					OperationId: "GpmServiceGetService",
					Parameters: []*registry.PathParameters{
						&registry.PathParameters{
							Name:        "name",
							In:          "path",
							Description: "服务名称",
							Required:    true,
							Explode:     true,
							Schema: &registry.Schema{
								Type: "string",
							},
						},
					},
					Responses: map[string]*registry.PathResponse{
						"200": &registry.PathResponse{
							Description: "successful response (stream response)",
							Content: &registry.PathRequestBodyContent{
								ApplicationJson: &registry.ApplicationContent{
									Schema: &registry.Schema{Ref: "#/components/schemas/v1.GetServiceRsp"},
								},
							},
						},
					},
					Security: []*registry.PathSecurity{},
				},
				Patch: &registry.OpenAPIPathDocs{
					Tags:        []string{"GpmService"},
					Summary:     "修改服务信息",
					Description: "GpmService EditService",
					OperationId: "GpmServiceEditService",
					Parameters: []*registry.PathParameters{
						&registry.PathParameters{
							Name:        "name",
							In:          "path",
							Description: "EditServiceReq field name",
							Required:    true,
							Explode:     true,
							Schema: &registry.Schema{
								Type: "string",
							},
						},
					},
					RequestBody: &registry.PathRequestBody{
						Description: "EditService EditServiceReq",
						Content: &registry.PathRequestBodyContent{
							ApplicationJson: &registry.ApplicationContent{
								Schema: &registry.Schema{
									Ref: "#/components/schemas/v1.EditServiceReq",
								},
							},
						},
					},
					Responses: map[string]*registry.PathResponse{
						"200": &registry.PathResponse{
							Description: "successful response (stream response)",
							Content: &registry.PathRequestBodyContent{
								ApplicationJson: &registry.ApplicationContent{
									Schema: &registry.Schema{Ref: "#/components/schemas/v1.EditServiceRsp"},
								},
							},
						},
					},
					Security: []*registry.PathSecurity{},
				},
			},
			"/api/v1/Service/{name}/action/reboot": &registry.OpenAPIPath{
				Patch: &registry.OpenAPIPathDocs{
					Tags:        []string{"GpmService"},
					Summary:     "重启服务",
					Description: "GpmService RebootService",
					OperationId: "GpmServiceRebootService",
					Parameters: []*registry.PathParameters{
						&registry.PathParameters{
							Name:        "name",
							In:          "path",
							Description: "RebootServiceReq field name",
							Required:    true,
							Explode:     true,
							Schema: &registry.Schema{
								Type: "string",
							},
						},
					},
					RequestBody: &registry.PathRequestBody{
						Description: "RebootService RebootServiceReq",
						Content: &registry.PathRequestBodyContent{
							ApplicationJson: &registry.ApplicationContent{
								Schema: &registry.Schema{
									Ref: "#/components/schemas/v1.RebootServiceReq",
								},
							},
						},
					},
					Responses: map[string]*registry.PathResponse{
						"200": &registry.PathResponse{
							Description: "successful response (stream response)",
							Content: &registry.PathRequestBodyContent{
								ApplicationJson: &registry.ApplicationContent{
									Schema: &registry.Schema{Ref: "#/components/schemas/v1.RebootServiceRsp"},
								},
							},
						},
					},
					Security: []*registry.PathSecurity{},
				},
			},
			"/api/v1/Service/{name}/action/start": &registry.OpenAPIPath{
				Patch: &registry.OpenAPIPathDocs{
					Tags:        []string{"GpmService"},
					Summary:     "启动服务",
					Description: "GpmService StartService",
					OperationId: "GpmServiceStartService",
					Parameters: []*registry.PathParameters{
						&registry.PathParameters{
							Name:        "name",
							In:          "path",
							Description: "StartServiceReq field name",
							Required:    true,
							Explode:     true,
							Schema: &registry.Schema{
								Type: "string",
							},
						},
					},
					RequestBody: &registry.PathRequestBody{
						Description: "StartService StartServiceReq",
						Content: &registry.PathRequestBodyContent{
							ApplicationJson: &registry.ApplicationContent{
								Schema: &registry.Schema{
									Ref: "#/components/schemas/v1.StartServiceReq",
								},
							},
						},
					},
					Responses: map[string]*registry.PathResponse{
						"200": &registry.PathResponse{
							Description: "successful response (stream response)",
							Content: &registry.PathRequestBodyContent{
								ApplicationJson: &registry.ApplicationContent{
									Schema: &registry.Schema{Ref: "#/components/schemas/v1.StartServiceRsp"},
								},
							},
						},
					},
					Security: []*registry.PathSecurity{},
				},
			},
			"/api/v1/Service/{name}/action/stop": &registry.OpenAPIPath{
				Patch: &registry.OpenAPIPathDocs{
					Tags:        []string{"GpmService"},
					Summary:     "停止服务",
					Description: "GpmService StopService",
					OperationId: "GpmServiceStopService",
					Parameters: []*registry.PathParameters{
						&registry.PathParameters{
							Name:        "name",
							In:          "path",
							Description: "StopServiceReq field name",
							Required:    true,
							Explode:     true,
							Schema: &registry.Schema{
								Type: "string",
							},
						},
					},
					RequestBody: &registry.PathRequestBody{
						Description: "StopService StopServiceReq",
						Content: &registry.PathRequestBodyContent{
							ApplicationJson: &registry.ApplicationContent{
								Schema: &registry.Schema{
									Ref: "#/components/schemas/v1.StopServiceReq",
								},
							},
						},
					},
					Responses: map[string]*registry.PathResponse{
						"200": &registry.PathResponse{
							Description: "successful response (stream response)",
							Content: &registry.PathRequestBodyContent{
								ApplicationJson: &registry.ApplicationContent{
									Schema: &registry.Schema{Ref: "#/components/schemas/v1.StopServiceRsp"},
								},
							},
						},
					},
					Security: []*registry.PathSecurity{},
				},
			},
			"/api/v1/Service/{name}/rollback": &registry.OpenAPIPath{
				Post: &registry.OpenAPIPathDocs{
					Tags:        []string{"GpmService"},
					Summary:     "回滚服务",
					Description: "GpmService RollBackService",
					OperationId: "GpmServiceRollBackService",
					Parameters: []*registry.PathParameters{
						&registry.PathParameters{
							Name:        "name",
							In:          "path",
							Description: "RollbackServiceReq field name",
							Required:    true,
							Explode:     true,
							Schema: &registry.Schema{
								Type: "string",
							},
						},
					},
					RequestBody: &registry.PathRequestBody{
						Description: "RollBackService RollbackServiceReq",
						Content: &registry.PathRequestBodyContent{
							ApplicationJson: &registry.ApplicationContent{
								Schema: &registry.Schema{
									Ref: "#/components/schemas/v1.RollbackServiceReq",
								},
							},
						},
					},
					Responses: map[string]*registry.PathResponse{
						"200": &registry.PathResponse{
							Description: "successful response (stream response)",
							Content: &registry.PathRequestBodyContent{
								ApplicationJson: &registry.ApplicationContent{
									Schema: &registry.Schema{Ref: "#/components/schemas/v1.RollbackServiceRsp"},
								},
							},
						},
					},
					Security: []*registry.PathSecurity{},
				},
			},
			"/api/v1/Service/{name}/versions": &registry.OpenAPIPath{
				Get: &registry.OpenAPIPathDocs{
					Tags:        []string{"GpmService"},
					Summary:     "查看服务历史版本",
					Description: "GpmService ListServiceVersions",
					OperationId: "GpmServiceListServiceVersions",
					Parameters: []*registry.PathParameters{
						&registry.PathParameters{
							Name:        "name",
							In:          "path",
							Description: "ListServiceVersionsReq field name",
							Required:    true,
							Explode:     true,
							Schema: &registry.Schema{
								Type: "string",
							},
						},
					},
					Responses: map[string]*registry.PathResponse{
						"200": &registry.PathResponse{
							Description: "successful response (stream response)",
							Content: &registry.PathRequestBodyContent{
								ApplicationJson: &registry.ApplicationContent{
									Schema: &registry.Schema{Ref: "#/components/schemas/v1.ListServiceVersionsRsp"},
								},
							},
						},
					},
					Security: []*registry.PathSecurity{},
				},
			},
			"/api/v1/info": &registry.OpenAPIPath{
				Get: &registry.OpenAPIPathDocs{
					Tags:        []string{"GpmService"},
					Summary:     "gpm 信息",
					Description: "GpmService Info",
					OperationId: "GpmServiceInfo",
					Parameters:  []*registry.PathParameters{},
					Responses: map[string]*registry.PathResponse{
						"200": &registry.PathResponse{
							Description: "successful response (stream response)",
							Content: &registry.PathRequestBodyContent{
								ApplicationJson: &registry.ApplicationContent{
									Schema: &registry.Schema{Ref: "#/components/schemas/v1.InfoRsp"},
								},
							},
						},
					},
					Security: []*registry.PathSecurity{},
				},
			},
		},
		Components: &registry.OpenAPIComponents{
			SecuritySchemes: &registry.SecuritySchemes{},
			Schemas: map[string]*registry.Model{
				"v1.ExecReq": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"in": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.ExecIn",
						},
					},
					Required: []string{"in"},
				},
				"v1.ExecRsp": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"result": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.ExecResult",
						},
					},
				},
				"v1.LsReq": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"path": &registry.Schema{
							Type: "string",
						},
					},
					Required: []string{"path"},
				},
				"v1.LsRsp": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"files": &registry.Schema{
							Type:  "array",
							Items: &registry.Schema{Ref: "#/components/schemas/v1.FileInfo"},
						},
					},
				},
				"v1.ListServiceReq": &registry.Model{
					Type:       "object",
					Properties: map[string]*registry.Schema{},
				},
				"v1.ListServiceRsp": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"services": &registry.Schema{
							Type:  "array",
							Items: &registry.Schema{Ref: "#/components/schemas/v1.Service"},
						},
						"total": &registry.Schema{
							Type:   "integer",
							Format: "int64",
						},
					},
				},
				"v1.CreateServiceReq": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"spec": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.ServiceSpec",
						},
					},
					Required: []string{"spec"},
				},
				"v1.CreateServiceRsp": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"service": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.Service",
						},
					},
				},
				"v1.DeleteServiceReq": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"name": &registry.Schema{
							Type: "string",
						},
					},
					Required: []string{"name"},
				},
				"v1.DeleteServiceRsp": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"service": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.Service",
						},
					},
				},
				"v1.GetServiceReq": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"name": &registry.Schema{
							Type: "string",
						},
					},
					Required: []string{"name"},
				},
				"v1.GetServiceRsp": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"service": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.Service",
						},
					},
				},
				"v1.EditServiceReq": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"name": &registry.Schema{
							Type: "string",
						},
						"spec": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.EditServiceSpec",
						},
					},
					Required: []string{"spec"},
				},
				"v1.EditServiceRsp": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"service": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.Service",
						},
					},
				},
				"v1.RebootServiceReq": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"name": &registry.Schema{
							Type: "string",
						},
					},
					Required: []string{"name"},
				},
				"v1.RebootServiceRsp": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"service": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.Service",
						},
					},
				},
				"v1.StartServiceReq": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"name": &registry.Schema{
							Type: "string",
						},
					},
					Required: []string{"name"},
				},
				"v1.StartServiceRsp": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"service": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.Service",
						},
					},
				},
				"v1.StopServiceReq": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"name": &registry.Schema{
							Type: "string",
						},
					},
					Required: []string{"name"},
				},
				"v1.StopServiceRsp": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"service": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.Service",
						},
					},
				},
				"v1.RollbackServiceReq": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"name": &registry.Schema{
							Type: "string",
						},
						"revision": &registry.Schema{
							Type: "string",
						},
					},
					Required: []string{"name"},
				},
				"v1.RollbackServiceRsp": &registry.Model{
					Type:       "object",
					Properties: map[string]*registry.Schema{},
				},
				"v1.ListServiceVersionsReq": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"name": &registry.Schema{
							Type: "string",
						},
					},
					Required: []string{"name"},
				},
				"v1.ListServiceVersionsRsp": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"versions": &registry.Schema{
							Type:  "array",
							Items: &registry.Schema{Ref: "#/components/schemas/v1.ServiceVersion"},
						},
					},
				},
				"v1.InfoReq": &registry.Model{
					Type:       "object",
					Properties: map[string]*registry.Schema{},
				},
				"v1.InfoRsp": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"gpm": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.GpmInfo",
						},
					},
				},
				"v1.ExecIn": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"name": &registry.Schema{
							Type: "string",
						},
						"args": &registry.Schema{
							Type:  "array",
							Items: &registry.Schema{Type: "string"},
						},
						"dir": &registry.Schema{
							Type: "string",
						},
						"env": &registry.Schema{
							AdditionalProperties: &registry.Schema{},
						},
						"user": &registry.Schema{
							Type: "string",
						},
						"group": &registry.Schema{
							Type: "string",
						},
					},
					Required: []string{"name"},
				},
				"v1.ExecResult": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"result": &registry.Schema{
							Type: "string",
						},
					},
				},
				"v1.FileInfo": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"name": &registry.Schema{
							Type: "string",
						},
						"size": &registry.Schema{
							Type:   "integer",
							Format: "int64",
						},
						"mode": &registry.Schema{
							Type: "string",
						},
						"modTime": &registry.Schema{
							Type:   "integer",
							Format: "int64",
						},
						"IsDir": &registry.Schema{
							Type: "boolean",
						},
					},
				},
				"v1.Service": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"name": &registry.Schema{
							Type: "string",
						},
						"bin": &registry.Schema{
							Type: "string",
						},
						"args": &registry.Schema{
							Type:  "array",
							Items: &registry.Schema{Type: "string"},
						},
						"pid": &registry.Schema{
							Type:   "integer",
							Format: "int64",
						},
						"dir": &registry.Schema{
							Type: "string",
						},
						"env": &registry.Schema{
							AdditionalProperties: &registry.Schema{},
						},
						"sysProcAttr": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.SysProcAttr",
						},
						"log": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.ProcLog",
						},
						"version": &registry.Schema{
							Type: "string",
						},
						"autoRestart": &registry.Schema{
							Type:   "integer",
							Format: "int32",
						},
						"installFlag": &registry.Schema{
							Type:   "integer",
							Format: "int32",
						},
						"creationTimestamp": &registry.Schema{
							Type:   "integer",
							Format: "int64",
						},
						"updateTimestamp": &registry.Schema{
							Type:   "integer",
							Format: "int64",
						},
						"startTimestamp": &registry.Schema{
							Type:   "integer",
							Format: "int64",
						},
						"status": &registry.Schema{
							Type: "string",
							Enum: []string{"init", "running", "stopped", "failed", "upgrading"},
						},
						"msg": &registry.Schema{
							Type: "string",
						},
						"stat": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.Stat",
						},
					},
					Required: []string{"name", "bin"},
				},
				"v1.ServiceSpec": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"name": &registry.Schema{
							Type: "string",
						},
						"bin": &registry.Schema{
							Type: "string",
						},
						"args": &registry.Schema{
							Type:  "array",
							Items: &registry.Schema{Type: "string"},
						},
						"dir": &registry.Schema{
							Type: "string",
						},
						"env": &registry.Schema{
							AdditionalProperties: &registry.Schema{},
						},
						"sysProcAttr": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.SysProcAttr",
						},
						"log": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.ProcLog",
						},
						"version": &registry.Schema{
							Type: "string",
						},
						"autoRestart": &registry.Schema{
							Type:   "integer",
							Format: "int32",
						},
						"headerTrimPrefix": &registry.Schema{
							Type: "string",
						},
						"installFlag": &registry.Schema{
							Type:   "integer",
							Format: "int32",
						},
					},
					Required: []string{"name", "bin", "version"},
				},
				"v1.EditServiceSpec": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"bin": &registry.Schema{
							Type: "string",
						},
						"args": &registry.Schema{
							Type:  "array",
							Items: &registry.Schema{Type: "string"},
						},
						"dir": &registry.Schema{
							Type: "string",
						},
						"env": &registry.Schema{
							AdditionalProperties: &registry.Schema{},
						},
						"sysProcAttr": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.SysProcAttr",
						},
						"log": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.ProcLog",
						},
						"autoRestart": &registry.Schema{
							Type:   "integer",
							Format: "int32",
						},
					},
				},
				"v1.ServiceVersion": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"name": &registry.Schema{
							Type: "string",
						},
						"version": &registry.Schema{
							Type: "string",
						},
						"timestamp": &registry.Schema{
							Type:   "integer",
							Format: "int64",
						},
					},
				},
				"v1.GpmInfo": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"version": &registry.Schema{
							Type: "string",
						},
						"goos": &registry.Schema{
							Type: "string",
						},
						"arch": &registry.Schema{
							Type: "string",
						},
						"gov": &registry.Schema{
							Type: "string",
						},
						"pid": &registry.Schema{
							Type:   "integer",
							Format: "int32",
						},
						"stat": &registry.Schema{
							Type: "object",
							Ref:  "#/components/schemas/v1.Stat",
						},
						"upTime": &registry.Schema{
							Type:   "integer",
							Format: "int64",
						},
					},
				},
				"v1.SysProcAttr": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"chroot": &registry.Schema{
							Type: "string",
						},
						"uid": &registry.Schema{
							Type:   "integer",
							Format: "int32",
						},
						"user": &registry.Schema{
							Type: "string",
						},
						"gid": &registry.Schema{
							Type:   "integer",
							Format: "int32",
						},
						"group": &registry.Schema{
							Type: "string",
						},
					},
				},
				"v1.ProcLog": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"expire": &registry.Schema{
							Type:    "integer",
							Format:  "int32",
							Default: "30",
						},
						"maxSize": &registry.Schema{
							Type:   "integer",
							Format: "int64",
						},
					},
				},
				"v1.Stat": &registry.Model{
					Type: "object",
					Properties: map[string]*registry.Schema{
						"cpuPercent": &registry.Schema{
							Type:   "number",
							Format: "double",
						},
						"memory": &registry.Schema{},
						"memPercent": &registry.Schema{
							Type:   "number",
							Format: "float",
						},
					},
				},
			},
		},
	}
}

// Client API for GpmService service
// +gen:openapi
type GpmService interface {
	// gpm 检测 gpm 服务状态
	Healthz(ctx context.Context, in *Empty, opts ...client.CallOption) (*Empty, error)
	// gpm 升级
	UpdateSelf(ctx context.Context, opts ...client.CallOption) (GpmService_UpdateSelfService, error)
	// +gen:summary=gpm 信息
	// +gen:get=/api/v1/info
	Info(ctx context.Context, in *InfoReq, opts ...client.CallOption) (*InfoRsp, error)
	// +gen:summary=查询所有服务
	// +gen:get=/api/v1/Service
	ListService(ctx context.Context, in *ListServiceReq, opts ...client.CallOption) (*ListServiceRsp, error)
	// +gen:summary=查询单个服务
	// +gen:get=/api/v1/Service/{name}
	GetService(ctx context.Context, in *GetServiceReq, opts ...client.CallOption) (*GetServiceRsp, error)
	// +gen:summary=新建服务
	// +gen:post=/api/v1/Service
	CreateService(ctx context.Context, in *CreateServiceReq, opts ...client.CallOption) (*CreateServiceRsp, error)
	// +gen:summary=修改服务信息
	// +gen:patch=/api/v1/Service/{name}
	EditService(ctx context.Context, in *EditServiceReq, opts ...client.CallOption) (*EditServiceRsp, error)
	// +gen:summary=启动服务
	// +gen:patch=/api/v1/Service/{name}/action/start
	StartService(ctx context.Context, in *StartServiceReq, opts ...client.CallOption) (*StartServiceRsp, error)
	// +gen:summary=停止服务
	// +gen:patch=/api/v1/Service/{name}/action/stop
	StopService(ctx context.Context, in *StopServiceReq, opts ...client.CallOption) (*StopServiceRsp, error)
	// +gen:summary=重启服务
	// +gen:patch=/api/v1/Service/{name}/action/reboot
	RebootService(ctx context.Context, in *RebootServiceReq, opts ...client.CallOption) (*RebootServiceRsp, error)
	// +gen:summary=删除服务
	// +gen:delete=/api/v1/Service/{name}
	DeleteService(ctx context.Context, in *DeleteServiceReq, opts ...client.CallOption) (*DeleteServiceRsp, error)
	// 动态监听服务日志
	WatchServiceLog(ctx context.Context, in *WatchServiceLogReq, opts ...client.CallOption) (GpmService_WatchServiceLogService, error)
	// 远程安装服务
	InstallService(ctx context.Context, opts ...client.CallOption) (GpmService_InstallServiceService, error)
	// +gen:summary=查看服务历史版本
	// +gen:get=/api/v1/Service/{name}/versions
	ListServiceVersions(ctx context.Context, in *ListServiceVersionsReq, opts ...client.CallOption) (*ListServiceVersionsRsp, error)
	// 升级服务
	UpgradeService(ctx context.Context, opts ...client.CallOption) (GpmService_UpgradeServiceService, error)
	// +gen:summary=回滚服务
	// +gen:post=/api/v1/Service/{name}/rollback
	RollBackService(ctx context.Context, in *RollbackServiceReq, opts ...client.CallOption) (*RollbackServiceRsp, error)
	// +gen:summary=获取目录信息下文件列表
	// +gen:get=/api/v1/Action/ls
	Ls(ctx context.Context, in *LsReq, opts ...client.CallOption) (*LsRsp, error)
	// 拉取文件
	Pull(ctx context.Context, in *PullReq, opts ...client.CallOption) (GpmService_PullService, error)
	// 推送文件
	Push(ctx context.Context, opts ...client.CallOption) (GpmService_PushService, error)
	// +gen:summary=远程执行命令
	// +gen:post=/api/v1/Action/exec
	Exec(ctx context.Context, in *ExecReq, opts ...client.CallOption) (*ExecRsp, error)
	// 远程命令行交互
	Terminal(ctx context.Context, opts ...client.CallOption) (GpmService_TerminalService, error)
}

type gpmService struct {
	c    client.Client
	name string
}

func NewGpmService(name string, c client.Client) GpmService {
	return &gpmService{
		c:    c,
		name: name,
	}
}

func (c *gpmService) Healthz(ctx context.Context, in *Empty, opts ...client.CallOption) (*Empty, error) {
	req := c.c.NewRequest(c.name, "GpmService.Healthz", in)
	out := new(Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpmService) UpdateSelf(ctx context.Context, opts ...client.CallOption) (GpmService_UpdateSelfService, error) {
	req := c.c.NewRequest(c.name, "GpmService.UpdateSelf", &UpdateSelfReq{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &gpmServiceUpdateSelf{stream}, nil
}

type GpmService_UpdateSelfService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*UpdateSelfReq) error
	Recv() (*UpdateSelfRsp, error)
}

type gpmServiceUpdateSelf struct {
	stream client.Stream
}

func (x *gpmServiceUpdateSelf) Close() error {
	return x.stream.Close()
}

func (x *gpmServiceUpdateSelf) Context() context.Context {
	return x.stream.Context()
}

func (x *gpmServiceUpdateSelf) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gpmServiceUpdateSelf) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gpmServiceUpdateSelf) Send(m *UpdateSelfReq) error {
	return x.stream.Send(m)
}

func (x *gpmServiceUpdateSelf) Recv() (*UpdateSelfRsp, error) {
	m := new(UpdateSelfRsp)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gpmService) Info(ctx context.Context, in *InfoReq, opts ...client.CallOption) (*InfoRsp, error) {
	req := c.c.NewRequest(c.name, "GpmService.Info", in)
	out := new(InfoRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpmService) ListService(ctx context.Context, in *ListServiceReq, opts ...client.CallOption) (*ListServiceRsp, error) {
	req := c.c.NewRequest(c.name, "GpmService.ListService", in)
	out := new(ListServiceRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpmService) GetService(ctx context.Context, in *GetServiceReq, opts ...client.CallOption) (*GetServiceRsp, error) {
	req := c.c.NewRequest(c.name, "GpmService.GetService", in)
	out := new(GetServiceRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpmService) CreateService(ctx context.Context, in *CreateServiceReq, opts ...client.CallOption) (*CreateServiceRsp, error) {
	req := c.c.NewRequest(c.name, "GpmService.CreateService", in)
	out := new(CreateServiceRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpmService) EditService(ctx context.Context, in *EditServiceReq, opts ...client.CallOption) (*EditServiceRsp, error) {
	req := c.c.NewRequest(c.name, "GpmService.EditService", in)
	out := new(EditServiceRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpmService) StartService(ctx context.Context, in *StartServiceReq, opts ...client.CallOption) (*StartServiceRsp, error) {
	req := c.c.NewRequest(c.name, "GpmService.StartService", in)
	out := new(StartServiceRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpmService) StopService(ctx context.Context, in *StopServiceReq, opts ...client.CallOption) (*StopServiceRsp, error) {
	req := c.c.NewRequest(c.name, "GpmService.StopService", in)
	out := new(StopServiceRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpmService) RebootService(ctx context.Context, in *RebootServiceReq, opts ...client.CallOption) (*RebootServiceRsp, error) {
	req := c.c.NewRequest(c.name, "GpmService.RebootService", in)
	out := new(RebootServiceRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpmService) DeleteService(ctx context.Context, in *DeleteServiceReq, opts ...client.CallOption) (*DeleteServiceRsp, error) {
	req := c.c.NewRequest(c.name, "GpmService.DeleteService", in)
	out := new(DeleteServiceRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpmService) WatchServiceLog(ctx context.Context, in *WatchServiceLogReq, opts ...client.CallOption) (GpmService_WatchServiceLogService, error) {
	req := c.c.NewRequest(c.name, "GpmService.WatchServiceLog", &WatchServiceLogReq{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &gpmServiceWatchServiceLog{stream}, nil
}

type GpmService_WatchServiceLogService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*WatchServiceLogRsp, error)
}

type gpmServiceWatchServiceLog struct {
	stream client.Stream
}

func (x *gpmServiceWatchServiceLog) Close() error {
	return x.stream.Close()
}

func (x *gpmServiceWatchServiceLog) Context() context.Context {
	return x.stream.Context()
}

func (x *gpmServiceWatchServiceLog) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gpmServiceWatchServiceLog) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gpmServiceWatchServiceLog) Recv() (*WatchServiceLogRsp, error) {
	m := new(WatchServiceLogRsp)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gpmService) InstallService(ctx context.Context, opts ...client.CallOption) (GpmService_InstallServiceService, error) {
	req := c.c.NewRequest(c.name, "GpmService.InstallService", &InstallServiceReq{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &gpmServiceInstallService{stream}, nil
}

type GpmService_InstallServiceService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*InstallServiceReq) error
	Recv() (*InstallServiceRsp, error)
}

type gpmServiceInstallService struct {
	stream client.Stream
}

func (x *gpmServiceInstallService) Close() error {
	return x.stream.Close()
}

func (x *gpmServiceInstallService) Context() context.Context {
	return x.stream.Context()
}

func (x *gpmServiceInstallService) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gpmServiceInstallService) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gpmServiceInstallService) Send(m *InstallServiceReq) error {
	return x.stream.Send(m)
}

func (x *gpmServiceInstallService) Recv() (*InstallServiceRsp, error) {
	m := new(InstallServiceRsp)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gpmService) ListServiceVersions(ctx context.Context, in *ListServiceVersionsReq, opts ...client.CallOption) (*ListServiceVersionsRsp, error) {
	req := c.c.NewRequest(c.name, "GpmService.ListServiceVersions", in)
	out := new(ListServiceVersionsRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpmService) UpgradeService(ctx context.Context, opts ...client.CallOption) (GpmService_UpgradeServiceService, error) {
	req := c.c.NewRequest(c.name, "GpmService.UpgradeService", &UpgradeServiceReq{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &gpmServiceUpgradeService{stream}, nil
}

type GpmService_UpgradeServiceService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*UpgradeServiceReq) error
	Recv() (*UpgradeServiceRsp, error)
}

type gpmServiceUpgradeService struct {
	stream client.Stream
}

func (x *gpmServiceUpgradeService) Close() error {
	return x.stream.Close()
}

func (x *gpmServiceUpgradeService) Context() context.Context {
	return x.stream.Context()
}

func (x *gpmServiceUpgradeService) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gpmServiceUpgradeService) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gpmServiceUpgradeService) Send(m *UpgradeServiceReq) error {
	return x.stream.Send(m)
}

func (x *gpmServiceUpgradeService) Recv() (*UpgradeServiceRsp, error) {
	m := new(UpgradeServiceRsp)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gpmService) RollBackService(ctx context.Context, in *RollbackServiceReq, opts ...client.CallOption) (*RollbackServiceRsp, error) {
	req := c.c.NewRequest(c.name, "GpmService.RollBackService", in)
	out := new(RollbackServiceRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpmService) Ls(ctx context.Context, in *LsReq, opts ...client.CallOption) (*LsRsp, error) {
	req := c.c.NewRequest(c.name, "GpmService.Ls", in)
	out := new(LsRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpmService) Pull(ctx context.Context, in *PullReq, opts ...client.CallOption) (GpmService_PullService, error) {
	req := c.c.NewRequest(c.name, "GpmService.Pull", &PullReq{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &gpmServicePull{stream}, nil
}

type GpmService_PullService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*PullRsp, error)
}

type gpmServicePull struct {
	stream client.Stream
}

func (x *gpmServicePull) Close() error {
	return x.stream.Close()
}

func (x *gpmServicePull) Context() context.Context {
	return x.stream.Context()
}

func (x *gpmServicePull) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gpmServicePull) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gpmServicePull) Recv() (*PullRsp, error) {
	m := new(PullRsp)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gpmService) Push(ctx context.Context, opts ...client.CallOption) (GpmService_PushService, error) {
	req := c.c.NewRequest(c.name, "GpmService.Push", &PushReq{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &gpmServicePush{stream}, nil
}

type GpmService_PushService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*PushReq) error
	Recv() (*PushRsp, error)
}

type gpmServicePush struct {
	stream client.Stream
}

func (x *gpmServicePush) Close() error {
	return x.stream.Close()
}

func (x *gpmServicePush) Context() context.Context {
	return x.stream.Context()
}

func (x *gpmServicePush) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gpmServicePush) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gpmServicePush) Send(m *PushReq) error {
	return x.stream.Send(m)
}

func (x *gpmServicePush) Recv() (*PushRsp, error) {
	m := new(PushRsp)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gpmService) Exec(ctx context.Context, in *ExecReq, opts ...client.CallOption) (*ExecRsp, error) {
	req := c.c.NewRequest(c.name, "GpmService.Exec", in)
	out := new(ExecRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gpmService) Terminal(ctx context.Context, opts ...client.CallOption) (GpmService_TerminalService, error) {
	req := c.c.NewRequest(c.name, "GpmService.Terminal", &TerminalReq{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &gpmServiceTerminal{stream}, nil
}

type GpmService_TerminalService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*TerminalReq) error
	Recv() (*TerminalRsp, error)
}

type gpmServiceTerminal struct {
	stream client.Stream
}

func (x *gpmServiceTerminal) Close() error {
	return x.stream.Close()
}

func (x *gpmServiceTerminal) Context() context.Context {
	return x.stream.Context()
}

func (x *gpmServiceTerminal) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gpmServiceTerminal) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gpmServiceTerminal) Send(m *TerminalReq) error {
	return x.stream.Send(m)
}

func (x *gpmServiceTerminal) Recv() (*TerminalRsp, error) {
	m := new(TerminalRsp)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GpmService service
// +gen:openapi
type GpmServiceHandler interface {
	// gpm 检测 gpm 服务状态
	Healthz(context.Context, *Empty, *Empty) error
	// gpm 升级
	UpdateSelf(context.Context, GpmService_UpdateSelfStream) error
	// +gen:summary=gpm 信息
	// +gen:get=/api/v1/info
	Info(context.Context, *InfoReq, *InfoRsp) error
	// +gen:summary=查询所有服务
	// +gen:get=/api/v1/Service
	ListService(context.Context, *ListServiceReq, *ListServiceRsp) error
	// +gen:summary=查询单个服务
	// +gen:get=/api/v1/Service/{name}
	GetService(context.Context, *GetServiceReq, *GetServiceRsp) error
	// +gen:summary=新建服务
	// +gen:post=/api/v1/Service
	CreateService(context.Context, *CreateServiceReq, *CreateServiceRsp) error
	// +gen:summary=修改服务信息
	// +gen:patch=/api/v1/Service/{name}
	EditService(context.Context, *EditServiceReq, *EditServiceRsp) error
	// +gen:summary=启动服务
	// +gen:patch=/api/v1/Service/{name}/action/start
	StartService(context.Context, *StartServiceReq, *StartServiceRsp) error
	// +gen:summary=停止服务
	// +gen:patch=/api/v1/Service/{name}/action/stop
	StopService(context.Context, *StopServiceReq, *StopServiceRsp) error
	// +gen:summary=重启服务
	// +gen:patch=/api/v1/Service/{name}/action/reboot
	RebootService(context.Context, *RebootServiceReq, *RebootServiceRsp) error
	// +gen:summary=删除服务
	// +gen:delete=/api/v1/Service/{name}
	DeleteService(context.Context, *DeleteServiceReq, *DeleteServiceRsp) error
	// 动态监听服务日志
	WatchServiceLog(context.Context, *WatchServiceLogReq, GpmService_WatchServiceLogStream) error
	// 远程安装服务
	InstallService(context.Context, GpmService_InstallServiceStream) error
	// +gen:summary=查看服务历史版本
	// +gen:get=/api/v1/Service/{name}/versions
	ListServiceVersions(context.Context, *ListServiceVersionsReq, *ListServiceVersionsRsp) error
	// 升级服务
	UpgradeService(context.Context, GpmService_UpgradeServiceStream) error
	// +gen:summary=回滚服务
	// +gen:post=/api/v1/Service/{name}/rollback
	RollBackService(context.Context, *RollbackServiceReq, *RollbackServiceRsp) error
	// +gen:summary=获取目录信息下文件列表
	// +gen:get=/api/v1/Action/ls
	Ls(context.Context, *LsReq, *LsRsp) error
	// 拉取文件
	Pull(context.Context, *PullReq, GpmService_PullStream) error
	// 推送文件
	Push(context.Context, GpmService_PushStream) error
	// +gen:summary=远程执行命令
	// +gen:post=/api/v1/Action/exec
	Exec(context.Context, *ExecReq, *ExecRsp) error
	// 远程命令行交互
	Terminal(context.Context, GpmService_TerminalStream) error
}

func RegisterGpmServiceHandler(s server.Server, hdlr GpmServiceHandler, opts ...server.HandlerOption) error {
	type gpmServiceImpl interface {
		Healthz(ctx context.Context, in *Empty, out *Empty) error
		UpdateSelf(ctx context.Context, stream server.Stream) error
		Info(ctx context.Context, in *InfoReq, out *InfoRsp) error
		ListService(ctx context.Context, in *ListServiceReq, out *ListServiceRsp) error
		GetService(ctx context.Context, in *GetServiceReq, out *GetServiceRsp) error
		CreateService(ctx context.Context, in *CreateServiceReq, out *CreateServiceRsp) error
		EditService(ctx context.Context, in *EditServiceReq, out *EditServiceRsp) error
		StartService(ctx context.Context, in *StartServiceReq, out *StartServiceRsp) error
		StopService(ctx context.Context, in *StopServiceReq, out *StopServiceRsp) error
		RebootService(ctx context.Context, in *RebootServiceReq, out *RebootServiceRsp) error
		DeleteService(ctx context.Context, in *DeleteServiceReq, out *DeleteServiceRsp) error
		WatchServiceLog(ctx context.Context, stream server.Stream) error
		InstallService(ctx context.Context, stream server.Stream) error
		ListServiceVersions(ctx context.Context, in *ListServiceVersionsReq, out *ListServiceVersionsRsp) error
		UpgradeService(ctx context.Context, stream server.Stream) error
		RollBackService(ctx context.Context, in *RollbackServiceReq, out *RollbackServiceRsp) error
		Ls(ctx context.Context, in *LsReq, out *LsRsp) error
		Pull(ctx context.Context, stream server.Stream) error
		Push(ctx context.Context, stream server.Stream) error
		Exec(ctx context.Context, in *ExecReq, out *ExecRsp) error
		Terminal(ctx context.Context, stream server.Stream) error
	}
	type GpmService struct {
		gpmServiceImpl
	}
	h := &gpmServiceHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:        "GpmService.Info",
		Description: "GpmService.Info",
		Path:        []string{"/api/v1/info"},
		Method:      []string{"GET"},
		Body:        "*",
		Handler:     "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:        "GpmService.ListService",
		Description: "GpmService.ListService",
		Path:        []string{"/api/v1/Service"},
		Method:      []string{"GET"},
		Body:        "*",
		Handler:     "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:        "GpmService.GetService",
		Description: "GpmService.GetService",
		Path:        []string{"/api/v1/Service/{name}"},
		Method:      []string{"GET"},
		Body:        "*",
		Handler:     "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:        "GpmService.CreateService",
		Description: "GpmService.CreateService",
		Path:        []string{"/api/v1/Service"},
		Method:      []string{"POST"},
		Body:        "*",
		Handler:     "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:        "GpmService.EditService",
		Description: "GpmService.EditService",
		Path:        []string{"/api/v1/Service/{name}"},
		Method:      []string{"PATCH"},
		Body:        "*",
		Handler:     "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:        "GpmService.StartService",
		Description: "GpmService.StartService",
		Path:        []string{"/api/v1/Service/{name}/action/start"},
		Method:      []string{"PATCH"},
		Body:        "*",
		Handler:     "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:        "GpmService.StopService",
		Description: "GpmService.StopService",
		Path:        []string{"/api/v1/Service/{name}/action/stop"},
		Method:      []string{"PATCH"},
		Body:        "*",
		Handler:     "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:        "GpmService.RebootService",
		Description: "GpmService.RebootService",
		Path:        []string{"/api/v1/Service/{name}/action/reboot"},
		Method:      []string{"PATCH"},
		Body:        "*",
		Handler:     "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:        "GpmService.DeleteService",
		Description: "GpmService.DeleteService",
		Path:        []string{"/api/v1/Service/{name}"},
		Method:      []string{"DELETE"},
		Body:        "*",
		Handler:     "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:        "GpmService.ListServiceVersions",
		Description: "GpmService.ListServiceVersions",
		Path:        []string{"/api/v1/Service/{name}/versions"},
		Method:      []string{"GET"},
		Body:        "*",
		Handler:     "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:        "GpmService.RollBackService",
		Description: "GpmService.RollBackService",
		Path:        []string{"/api/v1/Service/{name}/rollback"},
		Method:      []string{"POST"},
		Body:        "*",
		Handler:     "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:        "GpmService.Ls",
		Description: "GpmService.Ls",
		Path:        []string{"/api/v1/Action/ls"},
		Method:      []string{"GET"},
		Body:        "*",
		Handler:     "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:        "GpmService.Exec",
		Description: "GpmService.Exec",
		Path:        []string{"/api/v1/Action/exec"},
		Method:      []string{"POST"},
		Body:        "*",
		Handler:     "rpc",
	}))
	opts = append(opts, server.OpenAPIHandler(NewGpmServiceOpenAPI()))
	return s.Handle(s.NewHandler(&GpmService{h}, opts...))
}

type gpmServiceHandler struct {
	GpmServiceHandler
}

func (h *gpmServiceHandler) Healthz(ctx context.Context, in *Empty, out *Empty) error {
	return h.GpmServiceHandler.Healthz(ctx, in, out)
}

func (h *gpmServiceHandler) UpdateSelf(ctx context.Context, stream server.Stream) error {
	return h.GpmServiceHandler.UpdateSelf(ctx, &gpmServiceUpdateSelfStream{stream})
}

type GpmService_UpdateSelfStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*UpdateSelfRsp) error
	Recv() (*UpdateSelfReq, error)
}

type gpmServiceUpdateSelfStream struct {
	stream server.Stream
}

func (x *gpmServiceUpdateSelfStream) Close() error {
	return x.stream.Close()
}

func (x *gpmServiceUpdateSelfStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gpmServiceUpdateSelfStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gpmServiceUpdateSelfStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gpmServiceUpdateSelfStream) Send(m *UpdateSelfRsp) error {
	return x.stream.Send(m)
}

func (x *gpmServiceUpdateSelfStream) Recv() (*UpdateSelfReq, error) {
	m := new(UpdateSelfReq)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *gpmServiceHandler) Info(ctx context.Context, in *InfoReq, out *InfoRsp) error {
	return h.GpmServiceHandler.Info(ctx, in, out)
}

func (h *gpmServiceHandler) ListService(ctx context.Context, in *ListServiceReq, out *ListServiceRsp) error {
	return h.GpmServiceHandler.ListService(ctx, in, out)
}

func (h *gpmServiceHandler) GetService(ctx context.Context, in *GetServiceReq, out *GetServiceRsp) error {
	return h.GpmServiceHandler.GetService(ctx, in, out)
}

func (h *gpmServiceHandler) CreateService(ctx context.Context, in *CreateServiceReq, out *CreateServiceRsp) error {
	return h.GpmServiceHandler.CreateService(ctx, in, out)
}

func (h *gpmServiceHandler) EditService(ctx context.Context, in *EditServiceReq, out *EditServiceRsp) error {
	return h.GpmServiceHandler.EditService(ctx, in, out)
}

func (h *gpmServiceHandler) StartService(ctx context.Context, in *StartServiceReq, out *StartServiceRsp) error {
	return h.GpmServiceHandler.StartService(ctx, in, out)
}

func (h *gpmServiceHandler) StopService(ctx context.Context, in *StopServiceReq, out *StopServiceRsp) error {
	return h.GpmServiceHandler.StopService(ctx, in, out)
}

func (h *gpmServiceHandler) RebootService(ctx context.Context, in *RebootServiceReq, out *RebootServiceRsp) error {
	return h.GpmServiceHandler.RebootService(ctx, in, out)
}

func (h *gpmServiceHandler) DeleteService(ctx context.Context, in *DeleteServiceReq, out *DeleteServiceRsp) error {
	return h.GpmServiceHandler.DeleteService(ctx, in, out)
}

func (h *gpmServiceHandler) WatchServiceLog(ctx context.Context, stream server.Stream) error {
	m := new(WatchServiceLogReq)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.GpmServiceHandler.WatchServiceLog(ctx, m, &gpmServiceWatchServiceLogStream{stream})
}

type GpmService_WatchServiceLogStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*WatchServiceLogRsp) error
}

type gpmServiceWatchServiceLogStream struct {
	stream server.Stream
}

func (x *gpmServiceWatchServiceLogStream) Close() error {
	return x.stream.Close()
}

func (x *gpmServiceWatchServiceLogStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gpmServiceWatchServiceLogStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gpmServiceWatchServiceLogStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gpmServiceWatchServiceLogStream) Send(m *WatchServiceLogRsp) error {
	return x.stream.Send(m)
}

func (h *gpmServiceHandler) InstallService(ctx context.Context, stream server.Stream) error {
	return h.GpmServiceHandler.InstallService(ctx, &gpmServiceInstallServiceStream{stream})
}

type GpmService_InstallServiceStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*InstallServiceRsp) error
	Recv() (*InstallServiceReq, error)
}

type gpmServiceInstallServiceStream struct {
	stream server.Stream
}

func (x *gpmServiceInstallServiceStream) Close() error {
	return x.stream.Close()
}

func (x *gpmServiceInstallServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gpmServiceInstallServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gpmServiceInstallServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gpmServiceInstallServiceStream) Send(m *InstallServiceRsp) error {
	return x.stream.Send(m)
}

func (x *gpmServiceInstallServiceStream) Recv() (*InstallServiceReq, error) {
	m := new(InstallServiceReq)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *gpmServiceHandler) ListServiceVersions(ctx context.Context, in *ListServiceVersionsReq, out *ListServiceVersionsRsp) error {
	return h.GpmServiceHandler.ListServiceVersions(ctx, in, out)
}

func (h *gpmServiceHandler) UpgradeService(ctx context.Context, stream server.Stream) error {
	return h.GpmServiceHandler.UpgradeService(ctx, &gpmServiceUpgradeServiceStream{stream})
}

type GpmService_UpgradeServiceStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*UpgradeServiceRsp) error
	Recv() (*UpgradeServiceReq, error)
}

type gpmServiceUpgradeServiceStream struct {
	stream server.Stream
}

func (x *gpmServiceUpgradeServiceStream) Close() error {
	return x.stream.Close()
}

func (x *gpmServiceUpgradeServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gpmServiceUpgradeServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gpmServiceUpgradeServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gpmServiceUpgradeServiceStream) Send(m *UpgradeServiceRsp) error {
	return x.stream.Send(m)
}

func (x *gpmServiceUpgradeServiceStream) Recv() (*UpgradeServiceReq, error) {
	m := new(UpgradeServiceReq)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *gpmServiceHandler) RollBackService(ctx context.Context, in *RollbackServiceReq, out *RollbackServiceRsp) error {
	return h.GpmServiceHandler.RollBackService(ctx, in, out)
}

func (h *gpmServiceHandler) Ls(ctx context.Context, in *LsReq, out *LsRsp) error {
	return h.GpmServiceHandler.Ls(ctx, in, out)
}

func (h *gpmServiceHandler) Pull(ctx context.Context, stream server.Stream) error {
	m := new(PullReq)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.GpmServiceHandler.Pull(ctx, m, &gpmServicePullStream{stream})
}

type GpmService_PullStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*PullRsp) error
}

type gpmServicePullStream struct {
	stream server.Stream
}

func (x *gpmServicePullStream) Close() error {
	return x.stream.Close()
}

func (x *gpmServicePullStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gpmServicePullStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gpmServicePullStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gpmServicePullStream) Send(m *PullRsp) error {
	return x.stream.Send(m)
}

func (h *gpmServiceHandler) Push(ctx context.Context, stream server.Stream) error {
	return h.GpmServiceHandler.Push(ctx, &gpmServicePushStream{stream})
}

type GpmService_PushStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*PushRsp) error
	Recv() (*PushReq, error)
}

type gpmServicePushStream struct {
	stream server.Stream
}

func (x *gpmServicePushStream) Close() error {
	return x.stream.Close()
}

func (x *gpmServicePushStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gpmServicePushStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gpmServicePushStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gpmServicePushStream) Send(m *PushRsp) error {
	return x.stream.Send(m)
}

func (x *gpmServicePushStream) Recv() (*PushReq, error) {
	m := new(PushReq)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *gpmServiceHandler) Exec(ctx context.Context, in *ExecReq, out *ExecRsp) error {
	return h.GpmServiceHandler.Exec(ctx, in, out)
}

func (h *gpmServiceHandler) Terminal(ctx context.Context, stream server.Stream) error {
	return h.GpmServiceHandler.Terminal(ctx, &gpmServiceTerminalStream{stream})
}

type GpmService_TerminalStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*TerminalRsp) error
	Recv() (*TerminalReq, error)
}

type gpmServiceTerminalStream struct {
	stream server.Stream
}

func (x *gpmServiceTerminalStream) Close() error {
	return x.stream.Close()
}

func (x *gpmServiceTerminalStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gpmServiceTerminalStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gpmServiceTerminalStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gpmServiceTerminalStream) Send(m *TerminalRsp) error {
	return x.stream.Send(m)
}

func (x *gpmServiceTerminalStream) Recv() (*TerminalReq, error) {
	m := new(TerminalReq)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
