// Code generated by proto-gen-validator. DO NOT EDIT.
// source: github.com/gpm2/gpm/proto/apis/gpm/v1/gpm.proto

package gpmv1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	is "github.com/lack-io/vine/util/is"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *Service) Validate() error {
	return m.ValidateE("")
}

func (m *Service) ValidateE(prefix string) error {
	errs := make([]error, 0)
	if int64(m.Id) != 0 {
	}
	if len(m.Name) == 0 {
		errs = append(errs, fmt.Errorf("field '%sname' is required", prefix))
	}
	if len(m.Bin) == 0 {
		errs = append(errs, fmt.Errorf("field '%sbin' is required", prefix))
	}
	if len(m.Status) != 0 {
		if !is.In([]string{"init", "running", "stopped", "failed", "upgrading"}, string(m.Status)) {
			errs = append(errs, fmt.Errorf("field '%sstatus' must in '[init,running,stopped,failed,upgrading]'", prefix))
		}
	}
	return is.MargeErr(errs...)
}

func (m *SysProcAttr) Validate() error {
	return m.ValidateE("")
}

func (m *SysProcAttr) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}

func (m *ProcLog) Validate() error {
	return m.ValidateE("")
}

func (m *ProcLog) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}

func (m *Stat) Validate() error {
	return m.ValidateE("")
}

func (m *Stat) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}

func (m *PageMeta) Validate() error {
	return m.ValidateE("")
}

func (m *PageMeta) ValidateE(prefix string) error {
	errs := make([]error, 0)
	if int64(m.Page) == 0 {
		m.Page = 1
	}
	if int64(m.Page) != 0 {
		if !(m.Page > 0) {
			errs = append(errs, fmt.Errorf("field '%spage' must great than '0'", prefix))
		}
	}
	if int64(m.Size) == 0 {
		m.Size = 10
	}
	if int64(m.Size) != 0 {
		if !(m.Size > 0) {
			errs = append(errs, fmt.Errorf("field '%ssize' must great than '0'", prefix))
		}
	}
	return is.MargeErr(errs...)
}
