name: Release
on:
  push:
    tags:
      - 'v*'
  pull_request:

jobs:

  deploy:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: Lint Go Code
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go install golang.org/x/lint/golint@latest
          make lint

      - name: Get Tag Version
        run: |
          echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "tag=${{ github.ref_name }}"

      - name: Changelog
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go install github.com/lack-io/changelog@latest

      - name: Build Tar
        run: make tar

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body_path: ./_output/CHANGELOG.md
          draft: false
          prerelease: false
          files: |
            ./_output/gpm-darwin-arm64-${{ github.ref_name }}.tar.gz
            ./_output/gpm-darwin-amd64-${{ github.ref_name }}.tar.gz
            ./_output/gpm-linux-amd64-${{ github.ref_name }}.tar.gz
            ./_output/gpm-linux-arm64-${{ github.ref_name }}.tar.gz
            ./_output/gpm-windows-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
