// Code generated by proto-gen-validator
// source: github.com/vine-io/gpm/api/types/gpm/v1/gpm.proto

package gpmv1

import (
	fmt "fmt"
	is "github.com/vine-io/vine/util/is"
)

func (m *Service) Validate() error {
	return m.ValidateE("")
}

func (m *Service) ValidateE(prefix string) error {
	errs := make([]error, 0)
	if len(m.Name) == 0 {
		errs = append(errs, fmt.Errorf("field '%sname' is required", prefix))
	}
	if len(m.Bin) == 0 {
		errs = append(errs, fmt.Errorf("field '%sbin' is required", prefix))
	}
	if len(m.Status) != 0 {
		if !is.In([]string{"init", "running", "stopped", "failed", "upgrading"}, string(m.Status)) {
			errs = append(errs, fmt.Errorf("field '%sstatus' must in '[init,running,stopped,failed,upgrading]'", prefix))
		}
	}
	return is.MargeErr(errs...)
}

func (m *SysProcAttr) Validate() error {
	return m.ValidateE("")
}

func (m *SysProcAttr) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}

func (m *ServiceSpec) Validate() error {
	return m.ValidateE("")
}

func (m *ServiceSpec) ValidateE(prefix string) error {
	errs := make([]error, 0)
	if len(m.Name) == 0 {
		errs = append(errs, fmt.Errorf("field '%sname' is required", prefix))
	}
	if len(m.Bin) == 0 {
		errs = append(errs, fmt.Errorf("field '%sbin' is required", prefix))
	}
	if len(m.Version) == 0 {
		errs = append(errs, fmt.Errorf("field '%sversion' is required", prefix))
	}
	return is.MargeErr(errs...)
}

func (m *UpgradeSpec) Validate() error {
	return m.ValidateE("")
}

func (m *UpgradeSpec) ValidateE(prefix string) error {
	errs := make([]error, 0)
	if len(m.Name) == 0 {
		errs = append(errs, fmt.Errorf("field '%sname' is required", prefix))
	}
	if len(m.Version) == 0 {
		errs = append(errs, fmt.Errorf("field '%sversion' is required", prefix))
	}
	return is.MargeErr(errs...)
}

func (m *EditServiceSpec) Validate() error {
	return m.ValidateE("")
}

func (m *EditServiceSpec) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}

func (m *ProcLog) Validate() error {
	return m.ValidateE("")
}

func (m *ProcLog) ValidateE(prefix string) error {
	errs := make([]error, 0)
	if int64(m.Expire) == 0 {
		m.Expire = 30
	}
	if int64(m.Expire) != 0 {
	}
	return is.MargeErr(errs...)
}

func (m *Stat) Validate() error {
	return m.ValidateE("")
}

func (m *Stat) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}

func (m *GpmInfo) Validate() error {
	return m.ValidateE("")
}

func (m *GpmInfo) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}

func (m *Package) Validate() error {
	return m.ValidateE("")
}

func (m *Package) ValidateE(prefix string) error {
	errs := make([]error, 0)
	if len(m.Package) == 0 {
		errs = append(errs, fmt.Errorf("field '%spackage' is required", prefix))
	}
	if int64(m.Total) == 0 {
		errs = append(errs, fmt.Errorf("field '%stotal' is required", prefix))
	}
	return is.MargeErr(errs...)
}

func (m *InstallServiceIn) Validate() error {
	return m.ValidateE("")
}

func (m *InstallServiceIn) ValidateE(prefix string) error {
	errs := make([]error, 0)
	if m.Spec == nil {
		errs = append(errs, fmt.Errorf("field '%sspec' is required", prefix))
	} else {
		errs = append(errs, m.Spec.ValidateE(prefix+"spec."))
	}
	if m.Pack == nil {
		errs = append(errs, fmt.Errorf("field '%spack' is required", prefix))
	} else {
		errs = append(errs, m.Pack.ValidateE(prefix+"pack."))
	}
	return is.MargeErr(errs...)
}

func (m *InstallServiceResult) Validate() error {
	return m.ValidateE("")
}

func (m *InstallServiceResult) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}

func (m *UpgradeServiceIn) Validate() error {
	return m.ValidateE("")
}

func (m *UpgradeServiceIn) ValidateE(prefix string) error {
	errs := make([]error, 0)
	if m.Spec == nil {
		errs = append(errs, fmt.Errorf("field '%sspec' is required", prefix))
	} else {
		errs = append(errs, m.Spec.ValidateE(prefix+"spec."))
	}
	if m.Pack == nil {
		errs = append(errs, fmt.Errorf("field '%spack' is required", prefix))
	} else {
		errs = append(errs, m.Pack.ValidateE(prefix+"pack."))
	}
	return is.MargeErr(errs...)
}

func (m *UpgradeServiceResult) Validate() error {
	return m.ValidateE("")
}

func (m *UpgradeServiceResult) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}

func (m *ServiceLog) Validate() error {
	return m.ValidateE("")
}

func (m *ServiceLog) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}

func (m *ServiceVersion) Validate() error {
	return m.ValidateE("")
}

func (m *ServiceVersion) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}

func (m *FileInfo) Validate() error {
	return m.ValidateE("")
}

func (m *FileInfo) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}

func (m *UpdateIn) Validate() error {
	return m.ValidateE("")
}

func (m *UpdateIn) ValidateE(prefix string) error {
	errs := make([]error, 0)
	if len(m.Version) == 0 {
		errs = append(errs, fmt.Errorf("field '%sversion' is required", prefix))
	}
	return is.MargeErr(errs...)
}

func (m *UpdateResult) Validate() error {
	return m.ValidateE("")
}

func (m *UpdateResult) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}

func (m *ExecIn) Validate() error {
	return m.ValidateE("")
}

func (m *ExecIn) ValidateE(prefix string) error {
	errs := make([]error, 0)
	if len(m.Shell) == 0 {
		errs = append(errs, fmt.Errorf("field '%sshell' is required", prefix))
	}
	return is.MargeErr(errs...)
}

func (m *ExecResult) Validate() error {
	return m.ValidateE("")
}

func (m *ExecResult) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}

func (m *PullResult) Validate() error {
	return m.ValidateE("")
}

func (m *PullResult) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}

func (m *PushIn) Validate() error {
	return m.ValidateE("")
}

func (m *PushIn) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}

func (m *TerminalIn) Validate() error {
	return m.ValidateE("")
}

func (m *TerminalIn) ValidateE(prefix string) error {
	errs := make([]error, 0)
	if len(m.Command) == 0 {
		errs = append(errs, fmt.Errorf("field '%scommand' is required", prefix))
	}
	return is.MargeErr(errs...)
}

func (m *TerminalResult) Validate() error {
	return m.ValidateE("")
}

func (m *TerminalResult) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}
